import {Icon} from './icon';
export {Icon} from './icon';
import React, { useEffect, useRef, useState } from 'react';
import { type TabState, type WorkspaceTab } from '../core/tabs';
import type { Preferences } from '../core/preferences';
import type { AppState } from '../core/state';
const icons = { side: 'comment-discussion', file: 'file-code', terminal: 'terminal', diff: 'diff', preview: 'browser', lesson:'book', teaching:'hubot' };
export function Dock({ state, onSelect, onClose, onMove, onReopen, onHide, dirty, children, menu, initialWidth=48 }: {
  state: TabState; onSelect: (id: string) => void; onClose: (ids: string[]) => void; onMove: (id: string, before: string) => void; onReopen: () => void; onHide: () => void;
  initialWidth?:number; dirty: Record<string, boolean>; children: (tab: WorkspaceTab) => React.ReactNode; menu: React.ReactNode;
}) {
  const [adding, setAdding] = useState(false), [context, setContext] = useState<string | null>(null);
  const [width, setWidth] = useState(initialWidth);
  const drag = useRef<string | null>(null);
  useEffect(()=>{ const outside=(event:PointerEvent)=>{const target=event.target as Element;if(!target.closest('.dock-add-menu, [aria-label="添加标签页"], .dock-empty'))setAdding(false);};const escape=(event:KeyboardEvent)=>{if(event.key==='Escape'){setAdding(false);setContext(null);}};document.addEventListener('pointerdown',outside);document.addEventListener('keydown',escape);return()=>{document.removeEventListener('pointerdown',outside);document.removeEventListener('keydown',escape);};},[]);
  return <aside className="workbench-dock" style={{ width: `${width}%` }} aria-label="右侧工作区">
    <div className="dock-resizer" role="separator" aria-label="调整工作区宽度" aria-orientation="vertical" tabIndex={0} onKeyDown={e => { if (e.key === 'ArrowLeft') setWidth(w => Math.min(65,w+2)); if (e.key === 'ArrowRight') setWidth(w=>Math.max(30,w-2)); }} onPointerDown={e => { e.currentTarget.setPointerCapture(e.pointerId); }} onPointerMove={e=>{if(e.currentTarget.hasPointerCapture(e.pointerId)) setWidth(Math.max(30,Math.min(65,(window.innerWidth-e.clientX)/window.innerWidth*100))); }}/>
    <div className="dock-bar"><div className="dock-tabs" role="tablist" aria-label="工作区标签页">
      {state.tabs.map((tab,index)=><div className={`dock-tab ${state.activeId===tab.id?'active':''}`} key={tab.id} draggable onDragStart={e=>{drag.current=tab.id;e.dataTransfer.setData('text/plain',tab.id);}} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(drag.current)onMove(drag.current,tab.id);drag.current=null;}} onContextMenu={e=>{e.preventDefault();setContext(tab.id);}}>
        <button role="tab" id={`tab-${tab.id}`} aria-selected={state.activeId===tab.id} aria-controls={`pane-${tab.id}`} tabIndex={state.activeId===tab.id?0:-1} title={tab.title} onClick={()=>onSelect(tab.id)} onKeyDown={e=>{const next=e.key==='ArrowRight'?state.tabs[(index+1)%state.tabs.length]:e.key==='ArrowLeft'?state.tabs[(index-1+state.tabs.length)%state.tabs.length]:null;if(next){e.preventDefault();onSelect(next.id);document.getElementById(`tab-${next.id}`)?.focus();}}}><Icon name={icons[tab.kind]}/><span>{tab.title}</span>{dirty[tab.id]&&<span className="dirty-dot" aria-label="未保存"/>}</button>
        <button className="tab-close" aria-label={`关闭 ${tab.title}`} title="关闭标签页" onClick={()=>onClose([tab.id])}><Icon name="close"/></button>
      </div>)}
    </div><button className="icon-button" aria-label="添加标签页" title="添加标签页" onClick={()=>setAdding(!adding)}><Icon name="add"/></button><button className="icon-button" aria-label="隐藏右侧工作区" title="隐藏工作区，保留所有标签" onClick={onHide}><Icon name="layout-sidebar-right"/></button></div>
    {adding&&<div className="dock-add-menu" onClick={()=>setAdding(false)}>{menu}<button disabled={!state.closed.length} onClick={onReopen}><Icon name="history"/>恢复最近关闭的标签 <kbd>⌘⇧T</kbd></button></div>}
    {context&&<div className="context-shield" onClick={()=>setContext(null)}><div className="dock-context" role="menu"><button onClick={()=>onClose([context])}>关闭标签页</button><button onClick={()=>onClose(state.tabs.filter(t=>t.id!==context).map(t=>t.id))}>关闭其他标签页</button><button onClick={()=>onClose(state.tabs.slice(state.tabs.findIndex(t=>t.id===context)+1).map(t=>t.id))}>关闭右侧标签页</button></div></div>}
    <div className="dock-content">{state.tabs.length?state.tabs.map(tab=><div key={tab.id} id={`pane-${tab.id}`} role="tabpanel" aria-labelledby={`tab-${tab.id}`} hidden={state.activeId!==tab.id} className="dock-pane">{children(tab)}</div>):<div className="dock-empty"><Icon name="files"/><h3>在这里并排学习</h3><p>用上方“＋”打开文件、辅助对话或终端。<br/>关闭标签不会删除内容。</p><button onClick={()=>setAdding(true)}>打开一个标签页</button>{!!state.closed.length&&<button onClick={onReopen}>恢复最近关闭</button>}</div>}</div>
  </aside>;
}
export type SettingsSection = 'general'|'profile'|'appearance'|'model'|'learning'|'editor'|'voice'|'reminders'|'data'|'shortcuts';
const categories: Array<[SettingsSection,string,string,string]> = [
  ['general','常规','settings-gear','发送 Enter 关窗 菜单栏 开机启动'],['profile','个人资料','account','昵称 名称 学习目标 每日 时间 统计'],['appearance','外观','paintcan','主题 浅色 深色 系统 字号 字体'],['model','模型与接口','hubot','API Key OpenAI DeepSeek 提供方 协议'],['learning','教学与规则','book','Study Coach grill 拷问 提示词 默认模式 回复详细程度 自定义'],['editor','编辑器','code','字号 缩进 行号 小地图 自动换行'],['voice','语音输入与朗读','unmute','麦克风 本机 识别 SenseVoice 自动朗读 语速 声音'],['reminders','提醒与打卡','bell','日期 时间 通知 每天'],['data','数据与备份','database','导出 恢复 本地 隐私'],['shortcuts','快捷键','keyboard','键盘 设置 新建 显示 隐藏 标签页 保存']
];
export function Settings({ value, onChange, state, section, onSection, sections, loginControl }: { value: Preferences; onChange: (p: Preferences)=>void; state: AppState; section: SettingsSection; onSection:(s:SettingsSection)=>void; sections:Partial<Record<SettingsSection,React.ReactNode>>; loginControl:React.ReactNode }) {
  const [search,setSearch]=useState('');
  const field=<K extends keyof Preferences>(key:K,v:Preferences[K])=>onChange({...value,[key]:v});
  const toggle=(key:'closeToTray'|'wordWrap'|'lineNumbers'|'minimap',label:string,detail:string)=><label className="setting-row"><span><strong>{label}</strong><small>{detail}</small></span><input type="checkbox" role="switch" checked={value[key]} onChange={e=>field(key,e.target.checked)}/></label>;
  const select=<K extends keyof Preferences>(key:K,label:string,options:Array<[Preferences[K],string]>)=><label className="setting-row"><span><strong>{label}</strong></span><select value={String(value[key])} onChange={e=>field(key,(typeof value[key]==='number'?Number(e.target.value):e.target.value) as Preferences[K])}>{options.map(([v,l])=><option value={String(v)} key={String(v)}>{l}</option>)}</select></label>;
  const own:Partial<Record<SettingsSection,React.ReactNode>>={
    general:<><h2>常规</h2>{select('sendKey','发送消息',[['enter','Enter 发送，Shift + Enter 换行'],['mod-enter','⌘ / Ctrl + Enter 发送']])}{toggle('closeToTray','关窗后留在菜单栏','关闭窗口后继续接收每日提醒；关闭此项则退出应用。')}<div className="setting-row">{loginControl}</div></>,
    profile:<><h2>个人资料</h2><p>此资料保存在本机，用于你的学习工作台。</p><label className="field-label">显示名称<input maxLength={40} value={value.name} onChange={e=>field('name',e.target.value)}/></label><label className="field-label">长期学习目标<textarea maxLength={1000} value={value.goal} onChange={e=>field('goal',e.target.value)} placeholder="例如：能独立开发和调试 AI 应用"/></label>{select('dailyMinutes','每天可用时间',([30,60,90,120,150,180] as const).map(v=>[v,`${v} 分钟`]))}<div className="profile-stats"><div><strong>{state.columns.length}</strong><small>学习栏目</small></div><div><strong>{new Set(state.checkins.map(c=>c.date)).size}</strong><small>打卡天数</small></div><div><strong>{state.columns.reduce((n,c)=>n+c.evidence.length,0)+state.practice.length}</strong><small>产出记录</small></div></div><small>打卡与记录数量不代表已掌握；能力页保留实际证据。</small></>,
    appearance:<><h2>外观</h2><p>选择整个工作台的显示方式。</p><div className="theme-choices">{(['light','dark','system'] as const).map(t=><button className={value.theme===t?'selected':''} key={t} aria-pressed={value.theme===t} onClick={()=>field('theme',t)}><Icon name={t==='light'?'lightbulb':t==='dark'?'color-mode':'device-desktop'}/>{({light:'浅色',dark:'深色',system:'跟随系统'})[t]}</button>)}</div>{select('fontSize','界面字号',[12,13,14,15,16,17,18].map(v=>[v,`${v} px`]))}<div className="appearance-sample"><strong>从知道，到能做</strong><p>先理解当前知识块，再用自己的话解释。</p><code>const nextStep = "开始学习";</code></div></>,
    learning:<><h2>教学与规则</h2>{select('defaultMode','新打开栏目时的默认模式',[['coach','学习教练'],['study-coach','Study Coach'],['grill','想法拷问']])}{select('replyStyle','讲解详细程度',[['concise','简短'],['balanced','适中'],['detailed','详细']])}<label className="field-label">补充教学偏好<textarea maxLength={6000} value={value.customInstructions} onChange={e=>field('customInstructions',e.target.value)} placeholder="例如：优先使用 Python，术语先举例再解释。"/></label><div className="rule-note"><strong>一直遵循的学习原则</strong><p>先学后评估 · 概念落到动作 · 只认自己的产出 · 一次推进一步</p><p>学习教练按课程小节推进；Study Coach 支持概念速懂与复习安排；想法拷问逐个检查假设与证据。</p></div></>,
    editor:<><h2>编辑器</h2>{select('codeSize','代码字号',[11,12,13,14,15,16,17,18,19,20].map(v=>[v,`${v} px`]))}{select('tabSize','缩进宽度',([2,4,8] as const).map(v=>[v,`${v} 个空格`]))}{toggle('wordWrap','自动换行','长代码在当前面板内换行。')}{toggle('lineNumbers','显示行号','保留聊天引用文件行号的定位能力。')}{toggle('minimap','显示代码小地图','在编辑器右侧显示文件概览。')}</>,
    shortcuts:<><h2>快捷键</h2>{[['打开设置','⌘ / Ctrl + ,'],['新建栏目','⌘ / Ctrl + N'],['折叠 / 展开侧栏','⌘ / Ctrl + B'],['显示 / 隐藏右侧工作区','⌘ / Ctrl + ⇧ + B'],['关闭当前右侧标签','⌘ / Ctrl + W'],['恢复最近关闭的标签','⌘ / Ctrl + ⇧ + T'],['保存当前代码','⌘ / Ctrl + S'],['切换标签（焦点在标签上）','← / →']].map(([name,key])=><div className="setting-row" key={name}><span>{name}</span><kbd>{key}</kbd></div>)}</>
  };
  const matches=categories.filter(([id,label,,keywords])=>`${label} ${keywords}`.toLowerCase().includes(search.trim().toLowerCase()));
  const shown=search.trim()?matches:categories.filter(([id])=>id===section);
  return <div className="settings-shell"><nav className="settings-nav" aria-label="设置分类"><div className="settings-search"><Icon name="search"/><input aria-label="搜索设置" value={search} placeholder="搜索设置" onChange={e=>setSearch(e.target.value)}/></div>{categories.map(([id,label,icon])=><button key={id} className={!search&&section===id?'selected':''} onClick={()=>{setSearch('');onSection(id);}}><Icon name={icon}/>{label}</button>)}<small className="settings-version">学习工作台 0.10.0<br/>本机版本</small></nav><div className="settings-detail">{search&&<p className="search-count">找到 {shown.length} 个设置分类</p>}{shown.map(([id])=><section className="settings-group" key={id}>{own[id]||sections[id]}</section>)}{!shown.length&&<div className="dock-empty">没有匹配的设置，试试“语音”“主题”或“发送”。</div>}</div></div>;
}
